# Calls a workflow that builds a release.

name: Build Release

on:
  workflow_call:
    secrets:
      CF_API_KEY:
        required: true
      WAGO_API_TOKEN:
        required: true
  push:
    tags:
      - '*.*.*'
      - '!**-alpha**'
      - '!**-Alpha**'
    paths-ignore:
      - '.github/**'

jobs:
  build:
      name: Build Package
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Project
          uses: actions/checkout@v4

        - name: Run LuaCheck
          uses: BigWigsMods/actions/luacheck@master
          with:
            config: https://raw.githubusercontent.com/SFX-WoW/shared/main/config/.luacheckrc

        - name: Run Packager
          uses: BigWigsMods/packager@v2
          env:
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
            GITHUB_OAUTH: ${{ secrets.TOKEN_GITHUB }}
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

  package:
      name: Package Release
      secrets:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}